# crear_faro_viejo_lowpoly.py - Faro viejo (M27)
import bpy, os, sys
from math import radians
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'scripts-reutilizables'))
from plantilla_asset import limpiar, mat, arena, iluminar, asentar, camara, shade_flat, guardar
escena = limpiar()
MAT_cal = mat('MAT_Faro_Cal', (0.93, 0.91, 0.83))
MAT_cal_osc = mat('MAT_Faro_Cal_Osc', (0.65, 0.30, 0.22))
MAT_roca = mat('MAT_Faro_Roca', (0.45, 0.43, 0.40))
MAT_metal = mat('MAT_Faro_Metal', (0.30, 0.28, 0.26))
MAT_techo = mat('MAT_Faro_Techo', (0.40, 0.32, 0.22))
MAT_lampara = mat('MAT_Faro_Lampara', (1.0, 0.95, 0.55), emisivo=((1.0, 0.92, 0.50), 1.5))
bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=1.6, depth=0.6, location=(0, 0, 0.3))
base = bpy.context.object; base.name = 'SM_Faro_Base'; base.data.materials.append(MAT_roca)
bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0.55, 0.30))
puerta = bpy.context.object; puerta.name = 'SM_Faro_Puerta'; puerta.scale = (0.40, 0.10, 0.45); puerta.data.materials.append(MAT_metal)
bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=1.0, depth=4.0, location=(0, 0, 2.6))
torre_b = bpy.context.object; torre_b.name = 'SM_Faro_Torre_B'; torre_b.data.materials.append(MAT_cal)
bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.85, depth=2.0, location=(0, 0, 5.6))
torre_r = bpy.context.object; torre_r.name = 'SM_Faro_Torre_R'; torre_r.data.materials.append(MAT_cal_osc)
bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.95, depth=0.20, location=(0, 0, 6.7))
gal = bpy.context.object; gal.name = 'SM_Faro_Galeria'; gal.data.materials.append(MAT_metal)
bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.55, depth=0.50, location=(0, 0, 7.05))
lamp = bpy.context.object; lamp.name = 'SM_Faro_Lampara'; lamp.data.materials.append(MAT_lampara)
bpy.ops.mesh.primitive_cone_add(vertices=10, radius1=0.65, radius2=0.05, depth=0.70, location=(0, 0, 7.65))
techo = bpy.context.object; techo.name = 'SM_Faro_Techo'; techo.data.materials.append(MAT_techo)
arena(radio=3.0); iluminar(escena); asentar(escena)
camara(escena, 'CAM_FaroViejo', (8.5, -10.0, 4.5), (0, 0, 3.5))
shade_flat(escena); guardar(escena, '27-Islas-Ubicaciones', 'faro_viejo')
